[package]
name = "dynamo_pubsub"
version = "0.1.0"
authors = ["Nathan Fuchs <fuchsnj@gmail.com>"]

[dependencies]
pubsub = "0.2"

[dependencies.aws_dynamodb]
git = "https://github.com/fuchsnj/rust_aws_dynamodb"